### ISSUE TITLE
`printf` displaying `<missing argument>` with `-interp-dasm`

### ISSUE THREAD

**Issue by catalin-hritcu** [secure-compilation/CompCert#5]
In the ASM interpreter (`-interp-dasm`), `printf` displays `<missing argument>` instead of the actual data to be printed. This is related to `printf` being a variadic function.

**Comment by jeremyThibault** [comment]
@AndrewTolmach pointed me to a location in `C2C.ml` where the signature in calls to `printf` is modified when interpreting.
