### ISSUE TITLE
`-dasm` output not easy to read and cannot print all instructions

### ISSUE THREAD

**Issue by catalin-hritcu** [secure-compilation/CompCert#6]
The output of our printer for ASM programs with compartments (`-dasm`) produces output (`.s.intf` file) that is not easy to read and that shows `<instr>` for some instructions.

**Comment by jeremyThibault** [comment]
Interfaces are now printed inside the `.s` files, at the top, as comments. Please let me know if I missed anything, otherwise I'll close the issue.

**Comment by catalin-hritcu** [comment]
Thanks @jeremyThibault. Since this works around the original problem, not fix it, I think the issue can stay open, just that it's much lower priority now.

I'll update the README to document the new way of seeing ASM interfaces, and remove the following text about `-dasm`:
> For debugging purposes one can also use a highly experimental printer for the
> ASM programs with compartments generated by SECOMP:
>    [compartments]$ make ccs1.s.intf
> This passes the `-dasm` flag to the compiler in order to generate a `.s.intf`
> file, which includes information about the compartment interfaces, but which is
> at the moment not easy to read and shows `<instr>` for some instructions (#6).

**Comment by catalin-hritcu** [comment]
Nevermind, this can indeed be closed. I hadn't seen that you changed what gets printed in the `intf` files (and was also confused about the -dasm flag).
